version:
  name: velociraptor
  version: 0.6.2-1
  commit: 11145fd4
  build_time: "2021-12-11T00:08:02+10:00"
Client:
  server_urls:
  - https://velo.socfortress.co:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQRbOnNcgVZXYGoTFzk8c7oTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjExMjIxMjIzOTQxWhcNMzEx
    MjE5MjIzOTQxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDOQlvpuyh13elsgQ6xhoQSi62Q6+t6TqEF
    YTuxvWcgxb3xVIiYbjoPcYyQBBZTPt+wZg5Vu+gBdzsK/9kwuv4KhpZZTl2wRkNx
    MjPSH6c+IIJ9qVCtHShz9uFNUJFwKlNCDGkhzsfmH5em87IYW7z146gvlwwq8ips
    ya2GYvupTQYtY2HGcK0z9PXasYNthMHAGzSQ4+6KieTZixfYvBkvNJSYMETYt3Rd
    e39DVkLPNT4eXEAitRxNP63uvIXMI9UkJvYCTeGiLNzPiksMCLYOOIL6dpYdfnfm
    a/JIJVI7hk/O2AE4xmlWrGQ5g3UIqc/cxODPsmNVHAok3xk7JaiFAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSq5k694y7zWHhCWzdokQTJ1eQg
    RTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAKoaw6AEPslxSg09emYKhJWmN2B/hm5mFp9C7JxvRNgzL
    U5DhFznfURNoyg3waAk1qks8iny/WuX0GHnK8bkSvgyYBapqry/jmcU1EVlNRpAf
    0o0sgu1mUM5q9xA1+Oxc2b9/FN96Z09x8WNSmwKwR49008tdgbrdV4+3rJHrI557
    7O+fkaTEcI3B71DfgmBBBauY8OVGSk+kGBm3o4bDk/kqiKBAT9vFrA+LIDg22nL7
    jzMYZmiqvn+0IGNmXdGryUtX/0fDy+CTbNwlzBUHxzECBXSdT3aUS6La9MfrrtNe
    NZr9FExn+7w0s/j7iwVJTM7WqAgRg15NoaDK16RqJg==
    -----END CERTIFICATE-----
  nonce: 7OKVn0qzO8w=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.6.2-1
    commit: 11145fd4
    build_time: "2021-12-11T00:08:02+10:00"
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
